name: Reusable workflow to build Java application

on:
  workflow_call:
    inputs:
      maven_opts:
        type: string
        required: false
    outputs:
      version:
        description: "Project version"
        value: ${{ jobs.build-workflow.outputs.version }}

jobs:
  build-workflow:
    name: Build Java app
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_project_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '10'
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Maven Build (skip tests)
        run: mvn -T 2 clean install -DskipTests ${{ inputs.maven_opts }}
      - uses: actions/upload-artifact@v3
#        id: github.refName === 'cellbase' || github.refName === 'opencga'
        with:
          name: build-folder
          path: build
      - id: get_project_version
        uses: avides/actions-project-version-check@v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: pom.xml
          only-return-version: true
      - name: test-version-from-check
        run: echo "Project version is " ${{ steps.get_project_version.outputs.version }}
