name: Delete docker workflow from DockerHub

on:
  workflow_call:
    inputs:
      cli:
        type: string
        required: true
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  deploy-docker-hub:
    name: Push Docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/login-action@v2
        with:
          username: DOCKER_HUB_USER
          password: DOCKER_HUB_PASSWORD
      - name: Deploy in Docker Hub
        run: ${{ inputs.cli }}