name: Reusable workflow to release in DockerHub

on:
  workflow_call:
    inputs:
      cli:
        type: string
        required: true
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
jobs:
  deploy-docker-hub:
    name: Push Docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-folder
          path: build
      - name: Chmod
        run: "find build -regex '.*sh' | while read file ; do chmod u+x $file ; done"
      - uses: docker/login-action@v1
        if: ${{ inputs.cli }}
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Deploy in Docker Hub
        run: ${{ inputs.cli }}
