name: Merge/Push in java-common-libs develop branch

on:
  push:
    branches:
      - develop
      - release-*

jobs:
  build:
    uses: ./.github/workflows/build-java-app-workflow.yml

  test:
    uses: ./.github/workflows/test-analysis.yml
    needs: build
    secrets: inherit
#    with:
#      report_context: development
#      report_dir: ${{ github.ref_name }}/java-common-libs/${{ github.sha }}

  deploy-maven:
    uses: ./.github/workflows/deploy-maven-repository-workflow.yml
    needs: test
    secrets: inherit
