name: Push java-common-libs develop

on:
  push:
    branches:
      - develop
      - release-*

jobs:

  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop

  test:
    uses: opencb/java-common-libs/.github/workflows/test-analysis.yml@develop
    needs: build
    secrets: inherit
    with:
      report_context: development
      report_dir: ${{ github.ref_name }}/java-common-libs/${{ github.sha }}

  deploy-maven:
    uses: opencb/java-common-libs/.github/workflows/deploy-maven-repository-workflow.yml@develop
    needs: build
    secrets: inherit
