name: Reusable workflow to build Java application

on:
  workflow_call:

jobs:
  build-workflow:
    name: Build Java app
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '10'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Maven Build (skip tests)
        run: mvn -T 2 clean install -DskipTests
      - name: Maven Validate
        run: mvn validate
