name: Release new java-common-libs version

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build-java-app-workflow.yml

  test:
    uses: ./.github/workflows/test-analysis.yml
    needs: build
    secrets: inherit

  deploy-maven:
    uses: ./.github/workflows/deploy-maven-repository-workflow.yml
    needs: test
    secrets: inherit

  release:
    uses: ./.github/workflows/release-github-workflow.yml
    needs: deploy-maven
