name: Release new java-common-libs version

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop

  test:
    uses: opencb/java-common-libs/.github/workflows/test-analysis.yml@develop
    needs: build
    secrets: inherit
    with:
      report_context: xetabase
      report_dir: java-common-libs

  deploy-maven:
    uses: opencb/java-common-libs/.github/workflows/deploy-maven-repository-workflow.yml@develop
    needs: test
    secrets: inherit

  release:
    uses: opencb/java-common-libs/.github/workflows/release-github-workflow.yml@develop
    needs: test
