name: Push java-common-libs task

on:
  push:
    branches:
      - TASK-*

jobs:
  build:
    uses: ./.github/workflows/build-java-app-workflow.yml

  test:
    uses: ./.github/workflows/test-analysis.yml
    needs: build
    secrets: inherit
    with:
      report_context: development
      report_dir: ${{ github.ref_name }}/java-common-libs/${{ github.sha }}
